# Generated by Django 2.2.7 on 2020-01-07 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ConyugeActual',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Persona')),
                ('fecha_matrimonio', models.DateField()),
                ('registro_civil', models.CharField(max_length=80, unique=True)),
                ('nro_acta', models.CharField(max_length=80, unique=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('main.persona',),
        ),
        migrations.CreateModel(
            name='NMunicipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NEstado')),
            ],
        ),
        migrations.CreateModel(
            name='NColonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('codigo_postal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NCodigoPostal')),
            ],
        ),
        migrations.AddField(
            model_name='ncodigopostal',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NMunicipio'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=250)),
                ('numero_ext', models.CharField(max_length=250)),
                ('numero_int', models.CharField(blank=True, max_length=250, null=True)),
                ('colonia', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('codigo_postal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.NColonia')),
            ],
        ),
        migrations.CreateModel(
            name='DatosBasicos',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Persona')),
                ('titulo', models.IntegerField(choices=[(0, 'Sr'), (1, 'Sra')])),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.IntegerField(choices=[(0, 'MASCULINO'), (1, 'FEMENINO')])),
                ('ciudad_de_origen', models.CharField(max_length=80, unique=True)),
                ('documento_migratorio', models.CharField(max_length=80, unique=True)),
                ('calidad_migratoria', models.CharField(max_length=80, unique=True)),
                ('folio_de_identificacion', models.CharField(max_length=80, unique=True)),
                ('emite_identificacion', models.CharField(max_length=80, unique=True)),
                ('clave_larga_distancia', models.IntegerField(unique=True)),
                ('telefono_casa', models.IntegerField(unique=True)),
                ('telefono_casa_2', models.IntegerField(unique=True)),
                ('extension', models.IntegerField(unique=True)),
                ('celular', models.IntegerField(unique=True)),
                ('celular_2', models.IntegerField(unique=True)),
                ('telefono_oficina', models.IntegerField(unique=True)),
                ('telefono_oficina_2', models.IntegerField(unique=True)),
                ('telefono_nextel', models.IntegerField(unique=True)),
                ('id_nextel', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('email_2', models.CharField(max_length=80, unique=True)),
                ('email_3', models.CharField(max_length=80, unique=True)),
                ('facebook', models.CharField(max_length=80, unique=True)),
                ('twitter', models.CharField(max_length=80, unique=True)),
                ('web', models.CharField(max_length=80, unique=True)),
                ('estado_civil', models.IntegerField(choices=[(0, 'CASADO'), (1, 'SOLTERO'), (2, 'DIVORCIADO'), (3, 'VIUDO')])),
                ('conyuge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ConyugeActual')),
                ('ocupacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Ocupacion')),
                ('pais_nacimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natural', to='main.Pais')),
                ('pais_nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacionalidad', to='main.Pais')),
                ('tipo_de_identificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TipoIdentificacion')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('main.persona',),
        ),
    ]
