# Generated by Django 2.2.7 on 2020-01-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbasicos',
            name='celular_2',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='clave_larga_distancia',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='conyuge_apellido_materno',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='conyuge_apellido_paterno',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='conyuge_nombre',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='email_2',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='email_3',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='emite_identificacion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='extension',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='facebook',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='fecha_matrimonio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='folio_de_identificacion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='id_nextel',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='nro_acta',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='registro_civil',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='telefono_casa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='telefono_casa_2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='telefono_nextel',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='telefono_oficina',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='telefono_oficina_2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='twitter',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='web',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
