# Generated by Django 2.2.7 on 2020-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200115_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbasicos',
            name='estado_civil',
            field=models.IntegerField(choices=[(0, 'Casado'), (1, 'Soltero'), (2, 'Divorciado'), (3, 'Viudo')]),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='sexo',
            field=models.IntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')]),
        ),
    ]
