# Generated by Django 2.2.7 on 2020-01-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200115_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbasicos',
            name='pais_nacimiento',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='pais_nacionalidad',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
