# Generated by Django 2.2.7 on 2020-01-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200122_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ncodigopostal',
            options={'verbose_name': 'Código Postal', 'verbose_name_plural': 'Códigos Postales'},
        ),
        migrations.AlterModelOptions(
            name='ocupacion',
            options={'verbose_name': 'Ocupación', 'verbose_name_plural': 'Ocupaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipoidentificacion',
            options={'verbose_name': 'Tipo de Identificación', 'verbose_name_plural': 'Tipos de Identificación'},
        ),
        migrations.RemoveField(
            model_name='datosbasicos',
            name='id_nextel',
        ),
        migrations.RemoveField(
            model_name='datosbasicos',
            name='telefono_nextel',
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='estado_civil',
            field=models.IntegerField(choices=[(0, 'Casado Bienes Mancomunados'), (4, 'Casado Bienes Separados'), (1, 'Soltero'), (2, 'Divorciado'), (3, 'Viudo')]),
        ),
    ]
