# Generated by Django 2.2.7 on 2020-01-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200127_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Tipo de trámite',
                'verbose_name_plural': 'Tipos de trámites',
            },
        ),
        migrations.AddField(
            model_name='datosbasicos',
            name='tipo_de_tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TipoTramite'),
        ),
    ]
