# Generated by Django 2.2.7 on 2020-01-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_datosbasicos_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbasicos',
            name='clave_larga_distancia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
