# Generated by Django 2.2.7 on 2020-01-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200131_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbasicos',
            name='emite_identificacion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='folio_de_identificacion',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
