# Generated by Django 2.2.7 on 2020-01-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200131_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosbasicos',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='calidad_migratoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='documento_migratorio',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='emite_identificacion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='folio_de_identificacion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
