# Generated by Django 2.2.7 on 2020-02-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200131_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosbasicos',
            name='fecha_creacion',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
