# Generated by Django 2.2.7 on 2020-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_datosbasicos_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbasicos',
            name='estado_civil',
            field=models.IntegerField(choices=[(0, 'Casado Bienes Mancomunados'), (4, 'Casado Bienes Separados'), (1, 'Soltero')]),
        ),
    ]
