# Generated by Django 2.2.10 on 2020-04-24 14:48

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200212_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosbasicos',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w\\d]*$'))]),
        ),
        migrations.AddField(
            model_name='datosbasicos',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w\\d]*$'))]),
        ),
    ]
